import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
//components
import Sidebar from '../../common/sidebar'
import Topbar from '../../common/Topbar'
import Footer from '../../common/footer'
import AccountDetails from './AccountDetails.js'
import BetHistory from './BetHistory'

export default function MyAccount() {
  return (
    <div >
      <Head>
        <title>Onyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body id="page-top">
        <div id="wrapper">
          <Sidebar />
          <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div id="content-wrapper" class="d-flex flex-column">
                <Topbar />
                
              </div>
              
              <div>
                <AccountDetails />
              </div>

              <div>
                <BetHistory />
              </div>
                
            </div>
          </div>
        </div>
      </body>

      <Footer />
    </div>
  )
}
