import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import { useRouter } from 'next/router'
//components
import Sidebar from '../../../common/sidebar'
import Topbar from '../../../common/Topbar'
import Footer from '../../../common/footer'
import BetInterface3x2 from '../../../common/BetInterface3x2'
import MLBdata from '../../../data/formatted.json'

const BetCard = ({ num, oddsdata }) => {
    return (
        <div class="col-xl-6 col-md-6 mb-4">
            <div class="card border-left-primary shadow h-100 py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <BetInterface3x2  
                            num={num}
                            oddsdata={oddsdata}
                        />
                    </div>
                </div>
            </div>
        </div>
    );
};

export default function SubmitBet() {
    const router = useRouter()
    const { gameID } = router.query

  return (
    <div >
      <Head>
        <title>Onyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body id="page-top">
        <div id="wrapper">
          <Sidebar />
          <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div id="content-wrapper" class="d-flex flex-column">
                <Topbar />
                
              </div>
              
              <div class="row container">
                <BetCard  
                    num={gameID}
                    oddsdata={MLBdata}
                />
              </div>
                
            </div>
          </div>
        </div>
      </body>

      <Footer />
    </div>
  )
}
