import Head from 'next/head'
import React from 'react'
import Image from 'next/image'
import { useRouter } from 'next/router'
import useSWR from 'swr'
//components
import Sidebar from '../../../../common/sidebar'
import Topbar from '../../../../common/Topbar'
import Footer from '../../../../common/footer'
import SubmitBetCard from './SubmitBetCard'
import currentOffers from './currentOffers'

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function SubmitBet() {
  const router = useRouter()
  const {
      query: { gameID, market, team },
    } = router

  const { data, error } = useSWR('/api/Odds/houseodds', fetcher)

  if (error) return <div>{error.message}</div>
  if (!data) return <div>Loading...</div>
  
  return (
    <div >
      <Head>
        <title>Onyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body id="page-top">
        <div id="wrapper">
          <Sidebar />
          <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div id="content-wrapper" class="d-flex flex-column">
                <Topbar />
              </div>
              
              <div class="row container card-body justify-content-center">
                <SubmitBetCard  
                    gameID = {gameID}
                    oddsdata={data}
                    market = {market}
                    team = {team}
                />
              </div>
              
              <div class="row container-fluid"> 
                <currentOffers  
                  gameID = {gameID}
                />
              </div>
            </div>
          </div>
        </div>
      </body>

      <Footer />
    </div>
  )
}
