import Head from 'next/head'
import React from 'react'
import { useRouter } from 'next/router'
import useSWR from 'swr'
//components
import Sidebar from '../../../../../common/sidebar'
import Topbar from '../../../../../common/Topbar'
import Footer from '../../../../../common/footer'
import SubmitBetCard from '../../../../../common/BetInterface3x2/SubmitBetCard'
import MakeOffer from './MakeOffer'
import TakeOffer from './TakeOffer'
import BidDetails from './BidDetails'

const fetcher = (url) => fetch(url).then((res) => res.json());

export default function market() {
  const router = useRouter()
  const {
      query: { gameID, market, team },
    } = router

  const { data, error } = useSWR('/api/Odds/offers', fetcher)

  if (error) return <div>{error.message} we ran into an error </div>
  if (!data) return <div>Loading...</div>
  
  return (
    <div class="p-0">
      <Head>
        <title>Onyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body id="page-top">
        <div id="wrapper">
          <Sidebar />
          <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div id="content-wrapper" class="d-flex flex-column">
                <Topbar />
              </div>
              
              {/* <div class="row container card-body justify-content-center pt-0">
                <Title 
                  gameID = {gameID}
                  oddsdata={JSON.parse(data.marketodds.raw)}
                  market = {market}
                  team = {team}
                />
              </div> */}

              <div class="row container card-body justify-content-center pt-0 pb-0">
                <SubmitBetCard  
                    gameID = {gameID}
                    oddsdata={JSON.parse(data.marketodds.raw)}
                    market = {market}
                    team = {team}
                />
              </div>

              <div class="row p-1 py-0">
                <BidDetails />
              </div>
              
              <div class="row">

                <TakeOffer 
                  gameID = {gameID}
                  oddsdata = {data.offersdata}
                  market = {market}
                  team = {team}
                />

                <MakeOffer 
                  gameID = {gameID}
                  oddsdata = {data.offersdata}
                  market = {market}
                  team = {team}
                />

              </div>

              
            </div>
          </div>
        </div>
      </body>

      <Footer />
    </div>
  )
}
