import Head from 'next/head'
//components
import FeaturedBets from './FeaturedBets'
import Sidebar from '../common/sidebar'
import Topbar from '../common/Topbar'
import Footer from '../common/footer'
import Description from './Description'
//import Redis from 'ioredis'
// import FeaturedBets2 from './FeaturedBets2'
// import useSWR from 'swr';

export default function Home() {
  return (
    <div >
      <Head>
        <title>Onyx</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body id="page-top">
        <div id="wrapper">
          <Sidebar />
          <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
              <div id="content-wrapper" class="d-flex flex-column">
                <Topbar />

              </div>
              <Description />
              <FeaturedBets />
              
            </div>
          </div>
        </div>
      </body>

      <Footer />
    </div>
  )
}

// export async function getServerSideProps() {
//   // let redis = new Redis("us1-upward-lioness-34844.upstash.io");
//   let redis = new Redis("rediss://:1ab8f665ce744567ba3c4ee12ed4c869@us1-upward-lioness-34844.upstash.io:34844");
//   //const data = await redis.incr("counter");
//   //redis.set('foo', 'bar');
//   //redis.hset("game","sport","soccer")
//   //redis.hset("game","gameid","123")
//   //redis.hset("game","odds",'{"home":"120", "away":30, "state":"New York"}')
//   // const data = await redis.get('foo')
//   //const data = await redis.hgetall("game")
//   const data = await redis.hgetall('odds')
//   redis.quit()
//   console.log(data.raw)
//   return { props: { data } }
// } 
